apiVersion: v1
kind: Pod
metadata:
  name:  sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container   
      image: aluracursos/sistema-noticias:1
      ports:
      - name:  server
        containerPort:  80
        protocol: TCP
      envFrom:
        - configMapRef: 
            name: sistema-configmap
