apiVersion: v1
kind: Pod
metadata:
  name: teste-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /pasta-de-arquivos
          name: volume-pod
  volumes:
    - name: volume-pod
      hostPath:
        path: /home/teste-volume
        type: DirectoryOrCreate
        